packages:
  - apps/*
  - packages/*
minimumReleaseAgeExclude:
  - "@types/node@22.20.2"
overrides:
  sharp: ^0.35.4
allowBuilds:
  browser-tabs-lock: false
  core-js: false
  esbuild: true
  fsevents: true
  lefthook: true
  workerd: true
